### ISSUE TITLE
ux, 성능 관련 문의

### ISSUE THREAD

**Issue by wooogi123** [naen-nae/naen-nae#14]
안녕하세요.

몇가지 문의사항이 있어 이슈 올립니다.

성능 관련
-  infinity scroll의 폰트 fetch시 이전 폰트 파일이 전부 fetch되지 않은 상태에서 지속적으로 새로운 폰트를 불러오는 현상
- 위의 문제로 특정 사이즈가 큰 폰트 파일이 fetch를 block하는 현상

ux 관련
- home - details 사이의 scroll 위치가 공유되는 현상
- mobile 환경에서 다수의 CardBox가 추가될 경우 길어진 dom으로 인한 render delay

위 사항들이 개선되면 좋을 것 같습니다 😃 

모바일 UI가 보기 편해서 가끔식 구경하고 있는데, 추가적인 개선이 더 있으면 좋을 것 같아 이슈 올려봅니다 👍

**Comment by Gumball12** [comment]
@wooogi123 

피드백 감사합니다! 해당 내용은 빠른 시일 내에 조치하도록 하겠습니다 (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

**Comment by wooogi123** [comment]
@Gumball12 제가 vue에 익숙하지 않아서 직접적인 기여가 어려운점이 아쉽네요 😂 
좋은 서비스 응원합니다 👍
