### ISSUE TITLE
Webpage not working

### ISSUE THREAD

**Issue by greatSumini** [naen-nae/naen-nae#17]
```
GET https://naen-nae.shj.rip/fonts.json 404
Uncaught (in promise) TypeError: Cannot read property 'json' of undefined
```

fonts.json에 문제가 있는 것 같아요 ㅇㅅㅇ.. 😢

**Comment by Gumball12** [comment]
@greatSumini 

앗 넵 확인했습니다. 폰트 파일이 많아져 actions에서 정상적으로 빌드가 진행되지 않은 것으로 보입니다. 현재 임시로 조치하였으며, 원인 파악해서 처리하겠습니다. 피드백 감사합니다!! (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧
