### ISSUE TITLE
한불 정부표준 타자기체 저작권 문제

### ISSUE THREAD

**Issue by rishubil** [naen-nae/naen-nae#34]
한불 정부표준 타자기체는 상상토끼의 탁탁공한영체의 무단도용으로 알려져 있는 것 같습니다.
자세한 내용은 아래 게시글을 참고해주세요.

https://blog.naver.com/clubhada/222463984525

**Comment by Gumball12** [comment]
@rishubil 

앗 감사합니다. '한불 정부표준 타자기체'를 버전 관리 상에서도 완전하게 제거하도록 하겠습니다.
또한 향후 폰트 추가 시 라이선스와 관련된 이슈를 좀 더 면밀하게 조사하여 추가하도록 하겠습니다.
감사합니다.

**Comment by Gumball12** [comment]
HEAD를 포함하여 모든 git history에서 해당 글꼴 제거하였습니다.
