### ISSUE TITLE
[질문] 폰트 슬라이더의 변경을 실시간 반영하지 않은 이유

### ISSUE THREAD

**Issue by spilist** [naen-nae/naen-nae#46]
폰트 슬라이더 UI를 보고 저는 드래그하면 그것이 좌측 픽셀 숫자에 실시간으로 반영되고, 아래 렌더링 결과도 같이 바뀔 거라고 생각했는데요. (https://fonts.google.com/ 처럼) 

지금처럼 끝까지 변경된 뒤 반영하도록 결정하신 이유가 궁금합니다. 퍼포먼스 때문인가요?

**Comment by Gumball12** [comment]
@spilist 

안녕하세요.

처음에는 Virtual Scroll을 도입하지 않아 렌더링 된 모든 폰트에 대해 Font Size가 갱신되었습니다.
다만, 언급하신 대로 퍼포먼스 이슈가 발생되어 이후 실시간으로 변경되지 않게끔 구성했습니다.
(Virtual Scroll은 [이 블로그](https://blog.logrocket.com/virtual-scrolling-core-principles-and-basic-implementation-in-react/)의 중간 즈음 보이는 그림에서 잘 나타나 있습니다.)

지금은 Virtual Scroll을 도입하였으며, 실제로 Viewport에 보일 요소들만을 Dom Tree에 추가시키고 있습니다.
이제 실시간으로 Font Size가 갱신되도록 구성해도 퍼포먼스 이슈는 발생되지 않겠네요.
또한 좀 더 괜찮은 사용자 경험을 전달할 수 있을 것 같습니다.

해당 기능은 이번 주말 즈음 추가될 것 같습니다.
피드백에 감사드립니다!
